import type { Language } from "./types";

/**
 * Registro de idiomas. `status`:
 * - available: contenido suficiente para diagnóstico + sesiones.
 * - beta: contenido inicial; el diagnóstico se apoya en vocabulario.
 * - planned: visible en la web pública; aún sin contenido.
 *
 * Añadir un idioma = añadir su entrada aquí + su carpeta en content/<code>/.
 */
export const LANGUAGES: Language[] = [
  {
    code: "en",
    name: "Inglés",
    englishName: "English",
    nativeName: "English",
    family: "Germánica (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 2,
    rtl: false,
    speechLocale: "en-US",
    phonemeSupport: true,
    grammarFeatures: ["articles", "phrasal-verbs", "aspect", "auxiliaries"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇬🇧",
  },
  {
    code: "fr",
    name: "Francés",
    englishName: "French",
    nativeName: "Français",
    family: "Romance (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 2,
    rtl: false,
    speechLocale: "fr-FR",
    phonemeSupport: false,
    grammarFeatures: ["gender", "articles", "liaison", "subjunctive"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇫🇷",
  },
  {
    code: "ja",
    name: "Japonés",
    englishName: "Japanese",
    nativeName: "日本語",
    family: "Japónica",
    writingSystems: ["hiragana", "katakana", "kanji"],
    difficulty: 5,
    rtl: false,
    speechLocale: "ja-JP",
    phonemeSupport: false,
    grammarFeatures: ["particles", "sov-order", "politeness-levels", "counters"],
    spaceSeparated: false,
    status: "available",
    flagEmoji: "🇯🇵",
  },
  {
    code: "es",
    name: "Español",
    englishName: "Spanish",
    nativeName: "Español",
    family: "Romance (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 1,
    rtl: false,
    speechLocale: "es-MX",
    phonemeSupport: false,
    grammarFeatures: ["gender", "subjunctive", "ser-estar", "clitics"],
    spaceSeparated: true,
    status: "planned",
    flagEmoji: "🇲🇽",
  },
  {
    code: "de",
    name: "Alemán",
    englishName: "German",
    nativeName: "Deutsch",
    family: "Germánica (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 3,
    rtl: false,
    speechLocale: "de-DE",
    phonemeSupport: false,
    grammarFeatures: ["cases", "gender", "v2-order", "separable-verbs"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇩🇪",
  },
  {
    code: "it",
    name: "Italiano",
    englishName: "Italian",
    nativeName: "Italiano",
    family: "Romance (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 1,
    rtl: false,
    speechLocale: "it-IT",
    phonemeSupport: false,
    grammarFeatures: ["gender", "articles", "subjunctive"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇮🇹",
  },
  {
    code: "pt",
    name: "Portugués",
    englishName: "Portuguese",
    nativeName: "Português",
    family: "Romance (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 1,
    rtl: false,
    speechLocale: "pt-BR",
    phonemeSupport: false,
    grammarFeatures: ["gender", "nasal-vowels", "personal-infinitive"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇧🇷",
  },
  {
    code: "ko",
    name: "Coreano",
    englishName: "Korean",
    nativeName: "한국어",
    family: "Coreánica",
    writingSystems: ["hangul"],
    difficulty: 5,
    rtl: false,
    speechLocale: "ko-KR",
    phonemeSupport: false,
    grammarFeatures: ["particles", "sov-order", "honorifics"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇰🇷",
  },
  {
    code: "zh",
    name: "Chino mandarín",
    englishName: "Mandarin Chinese",
    nativeName: "中文",
    family: "Sinotibetana",
    writingSystems: ["hanzi"],
    difficulty: 5,
    rtl: false,
    speechLocale: "zh-CN",
    phonemeSupport: false,
    grammarFeatures: ["tones", "measure-words", "aspect-particles"],
    spaceSeparated: false,
    status: "available",
    flagEmoji: "🇨🇳",
  },
  {
    code: "ru",
    name: "Ruso",
    englishName: "Russian",
    nativeName: "Русский",
    family: "Eslava (indoeuropea)",
    writingSystems: ["cyrillic"],
    difficulty: 4,
    rtl: false,
    speechLocale: "ru-RU",
    phonemeSupport: false,
    grammarFeatures: ["cases", "aspect", "gender"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇷🇺",
  },
  {
    code: "ar",
    name: "Árabe",
    englishName: "Arabic",
    nativeName: "العربية",
    family: "Semítica (afroasiática)",
    writingSystems: ["arabic"],
    difficulty: 5,
    rtl: true,
    speechLocale: "ar-SA",
    phonemeSupport: false,
    grammarFeatures: ["root-patterns", "dual", "gender", "vso-order"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇸🇦",
  },
  {
    code: "nl",
    name: "Neerlandés",
    englishName: "Dutch",
    nativeName: "Nederlands",
    family: "Germánica (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 3,
    rtl: false,
    speechLocale: "nl-NL",
    phonemeSupport: false,
    grammarFeatures: ["v2-order", "de-het", "separable-verbs"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇳🇱",
  },
  {
    code: "sv",
    name: "Sueco",
    englishName: "Swedish",
    nativeName: "Svenska",
    family: "Germánica (indoeuropea)",
    writingSystems: ["latin"],
    difficulty: 3,
    rtl: false,
    speechLocale: "sv-SE",
    phonemeSupport: false,
    grammarFeatures: ["v2-order", "en-ett", "pitch-accent"],
    spaceSeparated: true,
    status: "available",
    flagEmoji: "🇸🇪",
  },
];

export const NATIVE_LANGUAGE_OPTIONS = ["es", "en", "fr", "pt", "it", "de"] as const;

export function getLanguage(code: string): Language | undefined {
  return LANGUAGES.find((l) => l.code === code);
}

export function learnableLanguages(): Language[] {
  return LANGUAGES.filter((l) => l.status !== "planned");
}
