import type { GrammarConcept } from "../types";

/** Neerlandés: programa gramatical A1 → C1. Revisión humana recomendada antes de ampliar. */
const es = (t: string) => ({ es: t });

export const NL_GRAMMAR: GrammarConcept[] = [
  {
    id: "nl:g:de-het",
    language: "nl",
    title: "Artículos: de y het",
    cefr: "A1",
    errorCategory: "nl:articles",
    summary: "El neerlandés tiene dos artículos definidos: de (masculino y femenino, la mayoría de palabras) y het (neutro). En plural siempre es de. El indefinido es een para todos.",
    whenToUse: ["Se aprende cada sustantivo con su artículo: de man, de vrouw, het huis."],
    formation: ["Plural: siempre de (de huizen).", "Diminutivos en -je siempre het: het meisje, het huisje.", "Palabras de dos sílabas con be-, ge-, ver-, ont- suelen ser het: het gesprek."],
    commonMistakes: [
      { wrong: "de huis", right: "het huis", why: "huis es neutro." },
      { wrong: "het boeken", right: "de boeken", why: "En plural siempre de." },
    ],
    examples: [
      { text: "Het huis is groot.", translation: es("La casa es grande.") },
      { text: "De kinderen spelen buiten.", translation: es("Los niños juegan afuera.") },
    ],
    contrasts: [{ a: "het meisje (la niña)", b: "de vrouw (la mujer)", explanation: "El diminutivo -je hace neutro incluso a personas." }],
    exercises: [
      { type: "mc", prompt: "___ huis is oud.", options: ["Het", "De", "Een het", "Den"], answers: ["Het"], explanation: "huis → het." },
      { type: "mc", prompt: "___ boeken liggen op tafel.", options: ["De", "Het", "Den", "Des"], answers: ["De"], explanation: "Plural → de." },
      { type: "mc", prompt: "___ meisje leest.", options: ["Het", "De", "Den", "Die"], answers: ["Het"], explanation: "Diminutivo -je → het." },
      { type: "mc", prompt: "Ik heb ___ fiets. (una)", options: ["een", "de", "het", "één de"], answers: ["een"], explanation: "Indefinido: een." },
    ],
  },
  {
    id: "nl:g:word-order",
    language: "nl",
    title: "Orden de palabras: el verbo en 2.ª posición",
    cefr: "A1",
    errorCategory: "nl:word-order",
    summary: "En la oración principal el verbo conjugado va segundo. Si empiezas por otra cosa (tiempo, lugar), el sujeto pasa detrás del verbo (inversión).",
    whenToUse: ["Morgen ga ik naar Amsterdam (no «Morgen ik ga»)."],
    formation: ["Posición 1: sujeto, tiempo, lugar… · Posición 2: verbo · luego el resto.", "Preguntas sí/no: verbo primero: Woon jij hier?", "Con jij/je en inversión se pierde la -t: Jij werkt → Werk jij?"],
    commonMistakes: [
      { wrong: "Morgen ik werk thuis.", right: "Morgen werk ik thuis.", why: "Verbo en 2.ª posición → inversión." },
      { wrong: "Werkt jij morgen?", right: "Werk jij morgen?", why: "Tras inversión con jij, sin -t." },
    ],
    examples: [
      { text: "Vandaag blijf ik thuis.", translation: es("Hoy me quedo en casa.") },
      { text: "Spreek jij Nederlands?", translation: es("¿Hablas neerlandés?") },
    ],
    contrasts: [{ a: "Ik ga morgen.", b: "Morgen ga ik.", explanation: "El verbo no se mueve de la 2.ª posición." }],
    exercises: [
      { type: "mc", prompt: "Vanavond ___ ik tv.", options: ["kijk", "kijkt", "kijken", "ik kijk"], answers: ["kijk"], explanation: "Inversión: Vanavond kijk ik tv." },
      { type: "mc", prompt: "___ jij in Utrecht?", options: ["Woon", "Woont", "Wonen", "Gewoond"], answers: ["Woon"], explanation: "Pregunta con jij: sin -t." },
      { type: "correct", prompt: "Morgen ik ga naar school.", answers: ["Morgen ga ik naar school."], explanation: "Verbo en 2.ª posición." },
      { type: "mc", prompt: "In de zomer ___ we naar zee.", options: ["gaan", "we gaan", "gaat", "ga"], answers: ["gaan"], explanation: "Verbo segundo: In de zomer gaan we…" },
    ],
  },
  {
    id: "nl:g:perfectum",
    language: "nl",
    title: "Perfectum: hebben o zijn + participio",
    cefr: "A2",
    errorCategory: "nl:perfectum",
    summary: "El perfectum es el pasado más usado al hablar. Se forma con hebben o zijn + participio (ge-…-t/-d o irregular), que va al final de la frase.",
    whenToUse: ["Contar lo que pasó: Ik heb gisteren gewerkt."],
    formation: ["Participio regular: ge + raíz + t/d («'t kofschip»: t tras t, k, f, s, ch, p): gewerkt, gewoond.", "Irregulares: gegeten, gedronken, gezien, geweest.", "zijn con cambio de lugar o estado: Ik ben naar huis gegaan. Hij is ziek geworden."],
    commonMistakes: [
      { wrong: "Ik heb naar huis gegaan.", right: "Ik ben naar huis gegaan.", why: "Movimiento hacia un lugar → zijn." },
      { wrong: "Ik heb gewerkt gisteren.", right: "Ik heb gisteren gewerkt.", why: "El participio va al final." },
    ],
    examples: [
      { text: "We hebben pizza gegeten.", translation: es("Comimos pizza.") },
      { text: "Ze is naar Spanje verhuisd.", translation: es("Se mudó a España.") },
    ],
    contrasts: [{ a: "Ik heb gefietst. (monté en bici)", b: "Ik ben naar huis gefietst. (fui a casa en bici)", explanation: "Con destino → zijn." }],
    exercises: [
      { type: "mc", prompt: "Ik ___ gisteren hard gewerkt.", options: ["heb", "ben", "is", "hebt"], answers: ["heb"], explanation: "werken → hebben." },
      { type: "mc", prompt: "Zij ___ naar Amsterdam gegaan.", options: ["is", "heeft", "hebben", "ben"], answers: ["is"], explanation: "gaan con destino → zijn." },
      { type: "mc", prompt: "Wij hebben koffie ___. (drinken)", options: ["gedronken", "gedrinkt", "gedronk", "drinkt"], answers: ["gedronken"], explanation: "Participio irregular." },
      { type: "mc", prompt: "Hij heeft in Utrecht ___. (wonen)", options: ["gewoond", "gewoont", "gewonen", "woonde"], answers: ["gewoond"], explanation: "'t kofschip: n no está → -d." },
    ],
  },
  {
    id: "nl:g:separable",
    language: "nl",
    title: "Verbos separables: opbellen, meenemen…",
    cefr: "A2",
    errorCategory: "nl:separable-verbs",
    summary: "Muchos verbos llevan un prefijo que se separa en la oración principal y va al final: opbellen → Ik bel je morgen op.",
    whenToUse: ["Presente y pasado simple en oración principal: el prefijo va al final.", "Participio: ge entre prefijo y verbo: opgebeld."],
    formation: ["opbellen → ik bel … op · meenemen → ik neem … mee · aankomen → de trein komt … aan.", "Participio: opgebeld, meegenomen, aangekomen.", "Infinitivo con te: op te bellen."],
    commonMistakes: [
      { wrong: "Ik opbel je morgen.", right: "Ik bel je morgen op.", why: "El prefijo va al final." },
      { wrong: "Ik heb je geopbeld.", right: "Ik heb je opgebeld.", why: "ge va tras el prefijo." },
    ],
    examples: [
      { text: "De trein komt om acht uur aan.", translation: es("El tren llega a las ocho.") },
      { text: "Neem je paraplu mee!", translation: es("¡Llévate el paraguas!") },
    ],
    contrasts: [{ a: "Ik bel je op.", b: "Ik heb je opgebeld.", explanation: "Separado en presente; unido en participio." }],
    exercises: [
      { type: "mc", prompt: "Ik bel je vanavond ___.", options: ["op", "mee", "aan", "uit"], answers: ["op"], explanation: "opbellen → … op." },
      { type: "mc", prompt: "Hij heeft zijn laptop ___. (meenemen)", options: ["meegenomen", "gemeenomen", "meegenommen", "genomen mee"], answers: ["meegenomen"], explanation: "Participio: mee + genomen." },
      { type: "correct", prompt: "De bus aankomt om tien uur.", answers: ["De bus komt om tien uur aan."], explanation: "aankomen se separa." },
      { type: "mc", prompt: "Wanneer kom je ___? (volver: terugkomen)", options: ["terug", "aan", "op", "mee"], answers: ["terug"], explanation: "terugkomen → kom … terug." },
    ],
  },
  {
    id: "nl:g:subordinate",
    language: "nl",
    title: "Oraciones subordinadas: el verbo al final",
    cefr: "B1",
    errorCategory: "nl:subordinate",
    summary: "Después de conjunciones como dat, omdat, als, wanneer, terwijl o of, todos los verbos van al final de la subordinada.",
    whenToUse: ["Ik denk dat hij morgen komt.", "Ik blijf thuis omdat ik ziek ben."],
    formation: ["Conjunción + sujeto + … + verbo(s).", "Con dos verbos, ambos al final: …omdat ik moet werken.", "Si la subordinada va primero, la principal empieza por el verbo: Als het regent, blijf ik thuis."],
    commonMistakes: [
      { wrong: "…omdat ik ben moe.", right: "…omdat ik moe ben.", why: "Verbo al final tras omdat." },
      { wrong: "Als het regent, ik blijf thuis.", right: "Als het regent, blijf ik thuis.", why: "La subordinada ocupa la posición 1: sigue el verbo." },
    ],
    examples: [
      { text: "Ik weet niet of hij thuis is.", translation: es("No sé si está en casa.") },
      { text: "Omdat het koud was, bleven we binnen.", translation: es("Como hacía frío, nos quedamos dentro.") },
    ],
    contrasts: [{ a: "Ik ben moe.", b: "…omdat ik moe ben.", explanation: "El verbo se va al final en la subordinada." }],
    exercises: [
      { type: "mc", prompt: "Ik blijf thuis omdat ik ziek ___.", options: ["ben", "is", "was ik", "zijn"], answers: ["ben"], explanation: "Verbo al final: omdat ik ziek ben." },
      { type: "correct", prompt: "Ik denk dat hij komt morgen.", answers: ["Ik denk dat hij morgen komt."], explanation: "Tras dat, verbo al final." },
      { type: "mc", prompt: "Als je tijd hebt, ___ je me.", options: ["bel", "belt", "je belt", "bellen"], answers: ["bel"], explanation: "Tras la subordinada: verbo + sujeto (sin -t con je)." },
      { type: "mc", prompt: "Weet jij ___ de winkel open is?", options: ["of", "dat", "omdat", "als"], answers: ["of"], explanation: "Pregunta indirecta sí/no → of." },
    ],
  },
  {
    id: "nl:g:er",
    language: "nl",
    title: "La palabra er",
    cefr: "B1",
    errorCategory: "nl:er",
    summary: "er tiene varios usos: «hay» (er is/er zijn), «allí» (lugar ya mencionado), cantidad (Ik heb er twee = tengo dos) y combinado con preposiciones (erover, ermee) en lugar de «het».",
    whenToUse: ["Existencia: Er is een probleem.", "Cantidad: Hoeveel kinderen heb je? Ik heb er drie.", "Preposición + cosa: Ik denk erover (no «over het»)."],
    formation: ["er is + singular / er zijn + plural.", "er + preposición: ermee, erover, erop, ervan (met → mee).", "En subordinada o con verbo al final: …omdat ik er niet aan gedacht heb."],
    commonMistakes: [
      { wrong: "Ik denk over het.", right: "Ik denk erover.", why: "Con cosas: er + preposición." },
      { wrong: "Ik heb twee.", right: "Ik heb er twee.", why: "Con números sin sustantivo se necesita er." },
    ],
    examples: [
      { text: "Er zijn veel toeristen in de stad.", translation: es("Hay muchos turistas en la ciudad.") },
      { text: "Ik ben er blij mee.", translation: es("Estoy contento con ello.") },
    ],
    contrasts: [{ a: "Ik praat met hem. (persona)", b: "Ik praat erover. (cosa)", explanation: "Con cosas se usa er + preposición." }],
    exercises: [
      { type: "mc", prompt: "___ is een probleem met mijn computer.", options: ["Er", "Het", "Daar", "Hier"], answers: ["Er"], explanation: "Existencia → er is." },
      { type: "mc", prompt: "Hoeveel broers heb je? Ik heb ___ twee.", options: ["er", "het", "ze", "die"], answers: ["er"], explanation: "Cantidad sin sustantivo → er." },
      { type: "mc", prompt: "Ik moet ___ nog over nadenken.", options: ["er", "het", "dat", "hem"], answers: ["er"], explanation: "er … over (= sobre ello)." },
      { type: "mc", prompt: "Wat doe je met die pen? Ik schrijf ___.", options: ["ermee", "met het", "mee het", "ermet"], answers: ["ermee"], explanation: "er + met → ermee." },
    ],
  },
  {
    id: "nl:g:passive",
    language: "nl",
    title: "Pasiva con worden",
    cefr: "B2",
    errorCategory: "nl:passive",
    summary: "La pasiva se forma con worden + participio (presente/pasado) y con zijn + participio en los tiempos compuestos. El agente se introduce con door.",
    whenToUse: ["Cuando importa la acción más que quién la hace: Het huis wordt verkocht."],
    formation: ["Presente: wordt/worden + participio: Het huis wordt gebouwd.", "Pasado: werd/werden + participio.", "Perfecto: is/zijn + participio (sin geworden): Het huis is verkocht.", "Pasiva impersonal: Er wordt gedanst."],
    commonMistakes: [
      { wrong: "Het boek is geschreven geworden.", right: "Het boek is geschreven.", why: "En el perfecto pasivo se omite geworden." },
      { wrong: "Het huis wordt verkocht van de man.", right: "Het huis wordt verkocht door de man.", why: "Agente → door." },
    ],
    examples: [
      { text: "De brief wordt morgen verstuurd.", translation: es("La carta se envía mañana.") },
      { text: "Het museum werd in 1885 geopend.", translation: es("El museo se inauguró en 1885.") },
    ],
    contrasts: [{ a: "De deur wordt gesloten. (la están cerrando)", b: "De deur is gesloten. (está cerrada / ha sido cerrada)", explanation: "Proceso frente a resultado." }],
    exercises: [
      { type: "mc", prompt: "Het huis ___ volgend jaar gebouwd.", options: ["wordt", "is", "heeft", "werd"], answers: ["wordt"], explanation: "Pasiva presente/futuro: wordt." },
      { type: "mc", prompt: "De auto is gisteren ___. (repareren)", options: ["gerepareerd", "gerepareerd geworden", "repareerd", "gerepareert"], answers: ["gerepareerd"], explanation: "Perfecto pasivo sin geworden." },
      { type: "mc", prompt: "Het boek is geschreven ___ een bekende schrijver.", options: ["door", "van", "met", "bij"], answers: ["door"], explanation: "Agente → door." },
      { type: "mc", prompt: "In 1900 ___ de brug gebouwd.", options: ["werd", "wordt", "is geworden", "heeft"], answers: ["werd"], explanation: "Pasado simple pasivo: werd." },
    ],
  },
  {
    id: "nl:g:conditional",
    language: "nl",
    title: "Hipótesis e irrealidad: zou / zouden",
    cefr: "C1",
    errorCategory: "nl:conditional",
    summary: "Para hipótesis, cortesía y situaciones irreales se usa zou/zouden + infinitivo. En el pasado irreal: had/was + participio en la subordinada y zou hebben/zijn + participio (o had/was) en la principal.",
    whenToUse: ["Cortesía: Zou je me kunnen helpen?", "Irreal presente: Als ik rijk was, zou ik reizen.", "Irreal pasado: Als ik het had geweten, was ik gekomen."],
    formation: ["zou (ik/jij/hij) · zouden (wij/jullie/zij) + infinitivo.", "Als + pasado simple → zou + infinitivo.", "Als + had/was + participio → had/was + participio (o zou … hebben)."],
    commonMistakes: [
      { wrong: "Als ik tijd zou hebben, ik zou komen.", right: "Als ik tijd had, zou ik komen.", why: "En la subordinada se prefiere el pasado; y la principal invierte sujeto y verbo." },
      { wrong: "Als ik het wist had, …", right: "Als ik het had geweten, …", why: "Irreal pasado: had + participio." },
    ],
    examples: [
      { text: "Zou u het raam kunnen openen?", translation: es("¿Podría abrir la ventana?") },
      { text: "Als ik jou was, zou ik het niet doen.", translation: es("Yo que tú, no lo haría.") },
    ],
    contrasts: [{ a: "Als het regent, blijf ik thuis. (real)", b: "Als het zou regenen, zou ik thuisblijven. (hipotético)", explanation: "zou marca la hipótesis." }],
    exercises: [
      { type: "mc", prompt: "Als ik meer geld had, ___ ik een huis kopen.", options: ["zou", "zal", "wil", "had"], answers: ["zou"], explanation: "Irreal presente → zou + infinitivo." },
      { type: "mc", prompt: "___ je me morgen kunnen bellen?", options: ["Zou", "Zal", "Wordt", "Had"], answers: ["Zou"], explanation: "Cortesía → zou." },
      { type: "mc", prompt: "Als ik het had ___, was ik gekomen.", options: ["geweten", "weten", "wist", "wetend"], answers: ["geweten"], explanation: "Irreal pasado: had + participio." },
      { type: "mc", prompt: "Wij ___ graag meedoen.", options: ["zouden", "zou", "zullen", "zult"], answers: ["zouden"], explanation: "Plural → zouden." },
    ],
  },
];
