import type { GrammarConcept } from "../types";

/** Alemán A1–C1: continúa el programa de de/index.ts. Revisión humana recomendada. */
const es = (t: string) => ({ es: t });

export const DE_GRAMMAR_ADVANCED: GrammarConcept[] = [
  {
    id: "de:g:negation",
    language: "de",
    title: "Negación: nicht y kein",
    cefr: "A1",
    errorCategory: "de:negation",
    summary: "kein niega sustantivos con artículo indefinido o sin artículo (= «ningún/no … un»); nicht niega todo lo demás: verbos, adjetivos, adverbios y sustantivos con artículo definido.",
    whenToUse: ["Ich habe kein Auto (no tengo coche).", "Ich komme nicht. Das ist nicht mein Buch."],
    formation: ["kein se declina como ein: kein, keine, keinen…", "nicht va al final o delante de lo que niega: Ich verstehe das nicht. Er ist nicht müde."],
    commonMistakes: [
      { wrong: "Ich habe nicht ein Auto.", right: "Ich habe kein Auto.", why: "«no … un» → kein." },
      { wrong: "Ich habe keine Zeit nicht.", right: "Ich habe keine Zeit.", why: "Una sola negación." },
    ],
    examples: [
      { text: "Heute habe ich keine Lust.", translation: es("Hoy no tengo ganas.") },
      { text: "Das Wetter ist nicht so schlecht.", translation: es("El tiempo no está tan mal.") },
    ],
    contrasts: [{ a: "Ich trinke keinen Kaffee. (sustantivo)", b: "Ich trinke nicht. (verbo)", explanation: "kein para sustantivos; nicht para el resto." }],
    exercises: [
      { type: "mc", prompt: "Ich habe ___ Hunger.", options: ["keinen", "nicht", "kein", "nichts"], answers: ["keinen"], explanation: "der Hunger, acusativo → keinen." },
      { type: "mc", prompt: "Er kommt heute ___.", options: ["nicht", "kein", "keine", "nein"], answers: ["nicht"], explanation: "Negación de verbo → nicht." },
      { type: "mc", prompt: "Wir haben ___ Zeit.", options: ["keine", "kein", "nicht", "keinen"], answers: ["keine"], explanation: "die Zeit → keine." },
      { type: "correct", prompt: "Ich habe nicht ein Handy.", answers: ["Ich habe kein Handy."], explanation: "«no … un» → kein." },
    ],
  },
  {
    id: "de:g:perfekt",
    language: "de",
    title: "Perfekt: haben o sein + Partizip II",
    cefr: "A2",
    errorCategory: "de:perfekt",
    summary: "Al hablar, el pasado más usado es el Perfekt: haben o sein + participio al final de la frase. sein se usa con verbos de movimiento o cambio de estado (y con bleiben, sein, werden).",
    whenToUse: ["Contar lo que pasó: Ich habe gestern Fußball gespielt."],
    formation: ["Regulares: ge + raíz + t: gespielt, gekauft.", "Irregulares: ge + raíz (cambiada) + en: gegessen, getrunken, gegangen.", "Sin ge- los verbos en -ieren y con prefijo inseparable: studiert, besucht, verstanden."],
    commonMistakes: [
      { wrong: "Ich habe nach Berlin gefahren.", right: "Ich bin nach Berlin gefahren.", why: "Movimiento hacia un lugar → sein." },
      { wrong: "Ich habe gestudiert.", right: "Ich habe studiert.", why: "Verbos en -ieren sin ge-." },
    ],
    examples: [
      { text: "Wir haben lange geschlafen.", translation: es("Dormimos mucho.") },
      { text: "Sie ist nach Spanien geflogen.", translation: es("Voló a España.") },
    ],
    contrasts: [{ a: "Ich habe gegessen.", b: "Ich bin gegangen.", explanation: "haben para la mayoría; sein para movimiento/cambio." }],
    exercises: [
      { type: "mc", prompt: "Gestern ___ ich ins Kino gegangen.", options: ["bin", "habe", "ist", "hat"], answers: ["bin"], explanation: "gehen → sein." },
      { type: "mc", prompt: "Wir haben Pizza ___.", options: ["gegessen", "geesst", "gegesst", "essen"], answers: ["gegessen"], explanation: "Participio irregular." },
      { type: "mc", prompt: "Er hat in Wien ___.", options: ["studiert", "gestudiert", "studieren", "gestudieren"], answers: ["studiert"], explanation: "-ieren sin ge-." },
      { type: "correct", prompt: "Ich habe nach Hause gelaufen.", answers: ["Ich bin nach Hause gelaufen."], explanation: "Movimiento a un lugar → sein." },
    ],
  },
  {
    id: "de:g:modalverben",
    language: "de",
    title: "Verbos modales: können, müssen, wollen, dürfen…",
    cefr: "A2",
    errorCategory: "de:modal-verbs",
    summary: "El modal va conjugado en 2.ª posición y el otro verbo, en infinitivo, al final. En singular son irregulares y la 1.ª y 3.ª persona coinciden (ich kann, er kann).",
    whenToUse: ["können (poder/saber), müssen (tener que), wollen (querer), dürfen (tener permiso), sollen (deber), möchten (quisiera)."],
    formation: ["ich kann / du kannst / er kann / wir können.", "ich muss · ich will · ich darf · ich soll · ich möchte.", "Modal (posición 2) … infinitivo (final): Ich muss heute arbeiten."],
    commonMistakes: [
      { wrong: "Ich kann schwimmen gut.", right: "Ich kann gut schwimmen.", why: "El infinitivo va al final." },
      { wrong: "Er kannt Deutsch sprechen.", right: "Er kann Deutsch sprechen.", why: "er kann (sin -t)." },
    ],
    examples: [
      { text: "Darf ich hier rauchen?", translation: es("¿Puedo fumar aquí?") },
      { text: "Wir müssen morgen früh aufstehen.", translation: es("Mañana tenemos que levantarnos temprano.") },
    ],
    contrasts: [{ a: "Du musst nicht kommen. (no hace falta)", b: "Du darfst nicht kommen. (no puedes / prohibido)", explanation: "¡Ojo! müssen nicht ≠ «no debes»." }],
    exercises: [
      { type: "mc", prompt: "___ du mir helfen?", options: ["Kannst", "Kann", "Können", "Kannt"], answers: ["Kannst"], explanation: "du kannst." },
      { type: "mc", prompt: "Ich muss heute lange ___.", options: ["arbeiten", "arbeite", "gearbeitet", "arbeitet"], answers: ["arbeiten"], explanation: "Infinitivo al final." },
      { type: "mc", prompt: "Hier ___ man nicht parken. (prohibido)", options: ["darf", "muss", "will", "soll"], answers: ["darf"], explanation: "Prohibición → nicht dürfen." },
      { type: "mc", prompt: "Er ___ Arzt werden. (quiere)", options: ["will", "willt", "wollen", "wolle"], answers: ["will"], explanation: "er will." },
    ],
  },
  {
    id: "de:g:wechselpraepositionen",
    language: "de",
    title: "Preposiciones de doble caso: in, an, auf… (Wo? / Wohin?)",
    cefr: "B1",
    errorCategory: "de:prepositions",
    summary: "Nueve preposiciones (an, auf, hinter, in, neben, über, unter, vor, zwischen) llevan dativo si indican ubicación (Wo?) y acusativo si indican dirección o movimiento hacia un lugar (Wohin?).",
    whenToUse: ["Wo? → dativo: Das Buch liegt auf dem Tisch.", "Wohin? → acusativo: Ich lege das Buch auf den Tisch."],
    formation: ["Dativo: dem (m/n), der (f), den + -n (pl).", "Acusativo: den (m), die (f), das (n), die (pl).", "Contracciones: in dem → im, in das → ins, an dem → am."],
    commonMistakes: [
      { wrong: "Ich gehe in dem Park.", right: "Ich gehe in den Park.", why: "Dirección (Wohin?) → acusativo." },
      { wrong: "Das Bild hängt an die Wand.", right: "Das Bild hängt an der Wand.", why: "Ubicación (Wo?) → dativo." },
    ],
    examples: [
      { text: "Wir sitzen im Garten.", translation: es("Estamos sentados en el jardín.") },
      { text: "Stell die Flasche in den Kühlschrank!", translation: es("¡Pon la botella en el refrigerador!") },
    ],
    contrasts: [{ a: "Ich bin in der Stadt. (Wo?)", b: "Ich fahre in die Stadt. (Wohin?)", explanation: "Estar frente a ir." }],
    exercises: [
      { type: "mc", prompt: "Die Katze schläft auf ___ Sofa.", options: ["dem", "das", "den", "der"], answers: ["dem"], explanation: "Ubicación, das Sofa → dem." },
      { type: "mc", prompt: "Ich lege das Handy auf ___ Tisch.", options: ["den", "dem", "der", "das"], answers: ["den"], explanation: "Dirección, der Tisch → den." },
      { type: "mc", prompt: "Wir gehen heute ___ Kino.", options: ["ins", "im", "in dem", "in der"], answers: ["ins"], explanation: "Dirección: in das → ins." },
      { type: "mc", prompt: "Das Auto steht vor ___ Haus.", options: ["dem", "das", "den", "des"], answers: ["dem"], explanation: "Ubicación → dativo." },
    ],
  },
  {
    id: "de:g:adjektivendungen",
    language: "de",
    title: "Terminaciones de los adjetivos",
    cefr: "B1",
    errorCategory: "de:adjectives",
    summary: "Delante de un sustantivo, el adjetivo cambia según el artículo, el género y el caso. Regla práctica: si el artículo ya muestra el género/caso (der, die, das, dem…), el adjetivo lleva -e o -en; si no (ein, sin artículo), el adjetivo lo muestra.",
    whenToUse: ["Adjetivo antes del sustantivo: der alte Mann, ein alter Mann. (Tras el verbo sein, sin terminación: Der Mann ist alt.)"],
    formation: [
      "Tras der/die/das (nominativo): -e: der neue Laptop, die neue Stadt, das neue Auto.",
      "Tras dem/den/des y en plural definido: -en: mit dem neuen Laptop, die neuen Autos.",
      "Tras ein (nominativo): ein neuer Laptop (m), ein neues Auto (n), eine neue Stadt (f).",
    ],
    commonMistakes: [
      { wrong: "ein neue Laptop", right: "ein neuer Laptop", why: "ein no muestra el masculino: lo muestra el adjetivo (-er)." },
      { wrong: "mit dem neue Auto", right: "mit dem neuen Auto", why: "Tras dem → -en." },
    ],
    examples: [
      { text: "Ich suche eine günstige Wohnung.", translation: es("Busco un departamento económico.") },
      { text: "Das ist ein schönes Geschenk.", translation: es("Es un regalo precioso.") },
    ],
    contrasts: [{ a: "der kleine Hund", b: "ein kleiner Hund", explanation: "Si el artículo no marca el género, lo marca el adjetivo." }],
    exercises: [
      { type: "mc", prompt: "Das ist ein ___ Auto. (neu)", options: ["neues", "neue", "neuer", "neuen"], answers: ["neues"], explanation: "ein + neutro nominativo → -es." },
      { type: "mc", prompt: "Der ___ Mann ist mein Opa. (alt)", options: ["alte", "alter", "alten", "altes"], answers: ["alte"], explanation: "Tras der (nominativo) → -e." },
      { type: "mc", prompt: "Ich fahre mit dem ___ Zug. (schnell)", options: ["schnellen", "schnelle", "schneller", "schnelles"], answers: ["schnellen"], explanation: "Tras dem → -en." },
      { type: "mc", prompt: "Er hat einen ___ Hund. (groß)", options: ["großen", "großer", "große", "großes"], answers: ["großen"], explanation: "Acusativo masculino → -en." },
    ],
  },
  {
    id: "de:g:passiv",
    language: "de",
    title: "Pasiva con werden",
    cefr: "B2",
    errorCategory: "de:passive",
    summary: "La pasiva de proceso se forma con werden + participio (al final). El agente va con von + dativo. En pasado: wurde; en Perfekt: ist … worden.",
    whenToUse: ["Procesos, textos formales, noticias: Das Rathaus wird renoviert."],
    formation: ["Präsens: wird/werden + Partizip: Das Haus wird gebaut.", "Präteritum: wurde/wurden + Partizip.", "Perfekt: ist + Partizip + worden (no «geworden»).", "Con modal: muss repariert werden."],
    commonMistakes: [
      { wrong: "Das Haus ist gebaut geworden.", right: "Das Haus ist gebaut worden.", why: "En la pasiva el participio de werden es worden." },
      { wrong: "Das Buch wurde von Goethe geschrieben werden.", right: "Das Buch wurde von Goethe geschrieben.", why: "Sobra el infinitivo." },
    ],
    examples: [
      { text: "In Österreich wird Deutsch gesprochen.", translation: es("En Austria se habla alemán.") },
      { text: "Der Brief muss heute noch geschickt werden.", translation: es("La carta tiene que enviarse hoy mismo.") },
    ],
    contrasts: [{ a: "Die Tür wird geschlossen. (proceso)", b: "Die Tür ist geschlossen. (estado)", explanation: "werden = proceso; sein = resultado (Zustandspassiv)." }],
    exercises: [
      { type: "mc", prompt: "Das Auto ___ gerade repariert.", options: ["wird", "ist", "hat", "würde"], answers: ["wird"], explanation: "Pasiva de proceso: wird." },
      { type: "mc", prompt: "Die Brücke ___ 1990 gebaut.", options: ["wurde", "wird", "war", "hat"], answers: ["wurde"], explanation: "Pasado pasivo: wurde." },
      { type: "mc", prompt: "Der Täter ist verhaftet ___.", options: ["worden", "geworden", "werden", "wurde"], answers: ["worden"], explanation: "Perfekt pasivo: ist … worden." },
      { type: "mc", prompt: "Das Buch wurde ___ einer jungen Autorin geschrieben.", options: ["von", "durch", "mit", "bei"], answers: ["von"], explanation: "Agente → von." },
    ],
  },
  {
    id: "de:g:konjunktiv2",
    language: "de",
    title: "Konjunktiv II: würde, wäre, hätte",
    cefr: "B2",
    errorCategory: "de:konjunktiv",
    summary: "El Konjunktiv II expresa irrealidad, deseos y cortesía. Con la mayoría de verbos se usa würde + infinitivo; con sein, haben y los modales se usan sus formas propias: wäre, hätte, könnte, müsste.",
    whenToUse: ["Cortesía: Könnten Sie mir helfen?", "Irreal: Wenn ich Zeit hätte, würde ich reisen.", "Pasado irreal: Wenn ich das gewusst hätte, wäre ich gekommen."],
    formation: ["würde + infinitivo (al final).", "sein → wäre · haben → hätte · können → könnte · müssen → müsste.", "Pasado: hätte/wäre + participio."],
    commonMistakes: [
      { wrong: "Wenn ich reich würde sein, …", right: "Wenn ich reich wäre, …", why: "sein → wäre (no würde sein)." },
      { wrong: "Wenn ich Zeit habe, würde ich kommen.", right: "Wenn ich Zeit hätte, würde ich kommen.", why: "Irreal → Konjunktiv II también en la condición." },
    ],
    examples: [
      { text: "Ich hätte gern ein Wasser.", translation: es("Quisiera un agua.") },
      { text: "An deiner Stelle würde ich das nicht machen.", translation: es("En tu lugar no lo haría.") },
    ],
    contrasts: [{ a: "Wenn ich Zeit habe, komme ich. (real)", b: "Wenn ich Zeit hätte, käme/würde ich kommen. (irreal)", explanation: "Real frente a hipotético." }],
    exercises: [
      { type: "mc", prompt: "Wenn ich reich ___, würde ich ein Haus kaufen.", options: ["wäre", "bin", "würde", "war"], answers: ["wäre"], explanation: "sein → wäre." },
      { type: "mc", prompt: "___ Sie mir bitte helfen?", options: ["Könnten", "Können", "Konnten", "Kannst"], answers: ["Könnten"], explanation: "Cortesía → könnten." },
      { type: "mc", prompt: "Wenn ich das gewusst ___, wäre ich gekommen.", options: ["hätte", "habe", "wäre", "würde"], answers: ["hätte"], explanation: "Pasado irreal: hätte + participio." },
      { type: "mc", prompt: "An deiner Stelle ___ ich mehr schlafen.", options: ["würde", "werde", "wurde", "wäre"], answers: ["würde"], explanation: "Consejo → würde + infinitivo." },
    ],
  },
  {
    id: "de:g:konjunktiv1",
    language: "de",
    title: "Konjunktiv I: el estilo indirecto de la prensa",
    cefr: "C1",
    errorCategory: "de:reported-speech",
    summary: "En noticias y textos formales, lo que dijo otra persona se reproduce con Konjunktiv I para mostrar distancia: Der Minister sagte, er sei zufrieden. Si coincide con el indicativo, se usa el Konjunktiv II.",
    whenToUse: ["Estilo indirecto formal (prensa, informes, textos académicos)."],
    formation: ["Raíz del infinitivo + -e, -est, -e, -en, -et, -en: er komme, er habe, er könne.", "sein: ich sei, du seist, er sei, wir seien, sie seien.", "Si coincide con el indicativo (sie haben) → Konjunktiv II (sie hätten).", "Pasado: er habe gesagt / er sei gekommen."],
    commonMistakes: [
      { wrong: "Er sagte, er ist krank. (en un periódico)", right: "Er sagte, er sei krank.", why: "Registro formal → Konjunktiv I." },
      { wrong: "Sie sagten, sie haben keine Zeit.", right: "Sie sagten, sie hätten keine Zeit.", why: "sie haben = indicativo → se usa hätten." },
    ],
    examples: [
      { text: "Die Firma teilte mit, die Preise würden steigen.", translation: es("La empresa comunicó que los precios subirían.") },
      { text: "Laut Polizei sei niemand verletzt worden.", translation: es("Según la policía, nadie resultó herido.") },
    ],
    contrasts: [{ a: "Er sagt, er ist müde. (coloquial)", b: "Er sagt, er sei müde. (formal)", explanation: "El Konjunktiv I marca que es discurso ajeno." }],
    exercises: [
      { type: "mc", prompt: "Der Sprecher sagte, die Lage ___ stabil.", options: ["sei", "ist", "wäre sein", "seien"], answers: ["sei"], explanation: "3.ª persona singular de sein → sei." },
      { type: "mc", prompt: "Sie erklärte, sie ___ keine Zeit gehabt.", options: ["habe", "hat", "hatte", "haben"], answers: ["habe"], explanation: "Konjunktiv I de haben: habe." },
      { type: "mc", prompt: "Die Studenten meinten, sie ___ mehr Unterstützung. (brauchen)", options: ["bräuchten", "brauchen", "brauche", "brauchten sie"], answers: ["bräuchten"], explanation: "sie brauchen = indicativo → Konjunktiv II." },
      { type: "mc", prompt: "Der Minister sagte, er ___ morgen nach Paris.", options: ["reise", "reist", "reisen", "gereist"], answers: ["reise"], explanation: "Konjunktiv I: er reise." },
    ],
  },
];
