import type { GrammarConcept } from "../types";

/** Sueco: programa gramatical A1 → C1. Revisión humana recomendada antes de ampliar. */
const es = (t: string) => ({ es: t });

export const SV_GRAMMAR: GrammarConcept[] = [
  {
    id: "sv:g:en-ett",
    language: "sv",
    title: "en / ett y el artículo definido pegado al final",
    cefr: "A1",
    errorCategory: "sv:articles",
    summary: "El sueco tiene dos géneros: en (común, ~75 % de las palabras) y ett (neutro). El artículo definido no va delante sino como sufijo: en bil → bilen (el coche), ett hus → huset (la casa).",
    whenToUse: ["Indefinido: en bok, ett äpple.", "Definido: boken, äpplet."],
    formation: ["en-palabras: + en/-n: bil → bilen, flicka → flickan.", "ett-palabras: + et/-t: hus → huset, äpple → äpplet.", "Plural definido: bilarna, husen."],
    commonMistakes: [
      { wrong: "en hus", right: "ett hus", why: "hus es ett-palabra." },
      { wrong: "den bil", right: "bilen", why: "El definido va como sufijo (den + adjetivo es otro caso)." },
    ],
    examples: [
      { text: "Huset är stort.", translation: es("La casa es grande.") },
      { text: "Jag har en katt. Katten heter Sigge.", translation: es("Tengo un gato. El gato se llama Sigge.") },
    ],
    contrasts: [{ a: "en bil → bilen", b: "ett hus → huset", explanation: "El sufijo depende del género." }],
    exercises: [
      { type: "mc", prompt: "Jag bor i ___ lägenhet.", options: ["en", "ett", "den", "det"], answers: ["en"], explanation: "lägenhet es en-palabra." },
      { type: "mc", prompt: "Jag äter ___ äpple.", options: ["ett", "en", "det", "den"], answers: ["ett"], explanation: "äpple es ett-palabra." },
      { type: "mc", prompt: "«el coche» = ___", options: ["bilen", "den bil", "bilet", "en bilen"], answers: ["bilen"], explanation: "en bil → bilen." },
      { type: "mc", prompt: "«la casa» = ___", options: ["huset", "husen", "hus", "det hus"], answers: ["huset"], explanation: "ett hus → huset." },
    ],
  },
  {
    id: "sv:g:v2",
    language: "sv",
    title: "El verbo en segunda posición",
    cefr: "A1",
    errorCategory: "sv:word-order",
    summary: "Como en alemán y neerlandés, el verbo conjugado va segundo en la oración principal. Si empiezas por un adverbio de tiempo o lugar, el sujeto va después del verbo.",
    whenToUse: ["Idag åker jag till Stockholm (no «Idag jag åker»)."],
    formation: ["Posición 1 (sujeto, tiempo, lugar…) + verbo + resto.", "Preguntas sí/no: verbo primero: Talar du svenska?", "El verbo no cambia con la persona: jag/du/han är."],
    commonMistakes: [
      { wrong: "Imorgon jag jobbar.", right: "Imorgon jobbar jag.", why: "Verbo en 2.ª posición." },
      { wrong: "Du talar svenska?", right: "Talar du svenska?", why: "Pregunta sí/no: verbo primero." },
    ],
    examples: [
      { text: "På helgen spelar vi fotboll.", translation: es("El fin de semana jugamos al fútbol.") },
      { text: "Bor du i Göteborg?", translation: es("¿Vives en Gotemburgo?") },
    ],
    contrasts: [{ a: "Jag dricker kaffe på morgonen.", b: "På morgonen dricker jag kaffe.", explanation: "El verbo se queda en 2.ª posición." }],
    exercises: [
      { type: "mc", prompt: "Idag ___ jag hemma.", options: ["stannar", "jag stannar", "stanna", "stannade jag"], answers: ["stannar"], explanation: "Idag stannar jag hemma." },
      { type: "correct", prompt: "Imorgon vi åker till Malmö.", answers: ["Imorgon åker vi till Malmö."], explanation: "Verbo en 2.ª posición." },
      { type: "mc", prompt: "___ du kaffe? (¿bebes?)", options: ["Dricker", "Du dricker", "Drick", "Druckit"], answers: ["Dricker"], explanation: "Pregunta sí/no: verbo primero." },
      { type: "mc", prompt: "På sommaren ___ vi till landet.", options: ["åker", "vi åker", "åka", "åkte vi"], answers: ["åker"], explanation: "Verbo segundo." },
    ],
  },
  {
    id: "sv:g:past",
    language: "sv",
    title: "Pretérito: los cuatro grupos de verbos",
    cefr: "A2",
    errorCategory: "sv:past-tense",
    summary: "El pasado depende del grupo del verbo: -ade (grupo 1), -de/-te (grupo 2), -dde (grupo 3) o cambio de vocal (irregulares). No cambia con la persona.",
    whenToUse: ["Acciones terminadas en un momento concreto del pasado: Igår jobbade jag."],
    formation: ["Grupo 1 (-ar): jobba → jobbade.", "Grupo 2 (-er): stänga → stängde, köpa → köpte.", "Grupo 3 (vocal larga): bo → bodde.", "Irregulares: gå → gick, se → såg, dricka → drack, vara → var."],
    commonMistakes: [
      { wrong: "Jag gådde hem.", right: "Jag gick hem.", why: "gå es irregular." },
      { wrong: "Jag köpade en bok.", right: "Jag köpte en bok.", why: "köpa es grupo 2 (tras p → -te)." },
    ],
    examples: [
      { text: "Igår åt vi middag på en restaurang.", translation: es("Ayer cenamos en un restaurante.") },
      { text: "Hon bodde i Uppsala i tre år.", translation: es("Vivió en Uppsala tres años.") },
    ],
    contrasts: [{ a: "jobbar (trabaja)", b: "jobbade (trabajó)", explanation: "El tiempo se marca en la terminación." }],
    exercises: [
      { type: "mc", prompt: "Igår ___ jag hela dagen. (jobba)", options: ["jobbade", "jobbar", "jobbte", "jobbat"], answers: ["jobbade"], explanation: "Grupo 1 → -ade." },
      { type: "mc", prompt: "Vi ___ till parken. (gå)", options: ["gick", "gådde", "går", "gått"], answers: ["gick"], explanation: "Irregular: gick." },
      { type: "mc", prompt: "Hon ___ en ny telefon. (köpa)", options: ["köpte", "köpade", "köpde", "köper"], answers: ["köpte"], explanation: "Grupo 2 con p → -te." },
      { type: "mc", prompt: "De ___ i Norge förut. (bo)", options: ["bodde", "bode", "boade", "bott"], answers: ["bodde"], explanation: "Grupo 3 → -dde." },
    ],
  },
  {
    id: "sv:g:adjectives",
    language: "sv",
    title: "Concordancia del adjetivo: stor, stort, stora",
    cefr: "A2",
    errorCategory: "sv:adjectives",
    summary: "El adjetivo añade -t con ett-palabras y -a en plural y en forma definida (den stora bilen).",
    whenToUse: ["Siempre que un adjetivo acompaña o describe a un sustantivo."],
    formation: ["en-palabra: en stor bil / bilen är stor.", "ett-palabra: ett stort hus / huset är stort.", "Plural: stora bilar · Definido: den stora bilen, det stora huset, de stora bilarna."],
    commonMistakes: [
      { wrong: "ett stor hus", right: "ett stort hus", why: "ett-palabra → -t." },
      { wrong: "den stor bilen", right: "den stora bilen", why: "Forma definida → -a." },
    ],
    examples: [
      { text: "Vi har ett litet kök.", translation: es("Tenemos una cocina pequeña.") },
      { text: "Den nya chefen är trevlig.", translation: es("El nuevo jefe es simpático.") },
    ],
    contrasts: [{ a: "en röd bil", b: "ett rött hus", explanation: "El adjetivo concuerda con el género." }],
    exercises: [
      { type: "mc", prompt: "Det är ett ___ problem. (stor)", options: ["stort", "stor", "stora", "storr"], answers: ["stort"], explanation: "ett-palabra → -t." },
      { type: "mc", prompt: "Jag gillar den ___ boken. (ny)", options: ["nya", "ny", "nytt", "nyt"], answers: ["nya"], explanation: "Definido → -a." },
      { type: "mc", prompt: "Vi köpte två ___ stolar. (billig)", options: ["billiga", "billig", "billigt", "billige"], answers: ["billiga"], explanation: "Plural → -a." },
      { type: "mc", prompt: "Bilen är ___. (snabb)", options: ["snabb", "snabbt", "snabba", "snabbe"], answers: ["snabb"], explanation: "en-palabra singular → sin terminación." },
    ],
  },
  {
    id: "sv:g:bisats",
    language: "sv",
    title: "Subordinadas: inte va antes del verbo",
    cefr: "B1",
    errorCategory: "sv:subordinate",
    summary: "En las subordinadas (att, eftersom, om, när, som…) no hay inversión y los adverbios como inte, aldrig o alltid van ANTES del verbo, no después.",
    whenToUse: ["Jag vet att han inte kommer (no «att han kommer inte»)."],
    formation: ["Principal: Han kommer inte.", "Subordinada: …att han inte kommer.", "Mismo orden con aldrig, alltid, ofta, redan."],
    commonMistakes: [
      { wrong: "Jag tror att hon kommer inte.", right: "Jag tror att hon inte kommer.", why: "En subordinada inte va antes del verbo." },
      { wrong: "…eftersom är jag trött.", right: "…eftersom jag är trött.", why: "Sin inversión en subordinadas." },
    ],
    examples: [
      { text: "Jag stannar hemma eftersom jag inte mår bra.", translation: es("Me quedo en casa porque no me encuentro bien.") },
      { text: "Hon säger att hon aldrig har varit i Spanien.", translation: es("Dice que nunca ha estado en España.") },
    ],
    contrasts: [{ a: "Han röker inte. (principal)", b: "…att han inte röker. (subordinada)", explanation: "La posición de inte cambia." }],
    exercises: [
      { type: "mc", prompt: "Jag vet att han ___ kommer idag.", options: ["inte", "inte kommer", "kommer inte", "aldrig kommer"], answers: ["inte"], explanation: "…att han inte kommer." },
      { type: "correct", prompt: "Hon säger att hon gillar inte kaffe.", answers: ["Hon säger att hon inte gillar kaffe."], explanation: "inte antes del verbo en subordinada." },
      { type: "mc", prompt: "Vi går ut om det ___ regnar.", options: ["inte", "regnar inte", "inte det", "aldrig det"], answers: ["inte"], explanation: "…om det inte regnar." },
      { type: "mc", prompt: "Jag är glad eftersom jag ___ klarade provet.", options: ["äntligen", "klarade", "har", "inte har"], answers: ["äntligen"], explanation: "El adverbio va antes del verbo en la subordinada." },
    ],
  },
  {
    id: "sv:g:perfect",
    language: "sv",
    title: "Perfecto con har + supino",
    cefr: "B1",
    errorCategory: "sv:perfect",
    summary: "El perfecto (har + supino) expresa experiencias y acciones pasadas conectadas con el presente, sin momento concreto. El supino es una forma propia: jobbat, köpt, bott, gått.",
    whenToUse: ["Experiencias: Har du varit i Norge?", "Resultados actuales: Jag har tappat nyckeln."],
    formation: ["Grupo 1: jobba → jobbat · Grupo 2: köpa → köpt · Grupo 3: bo → bott.", "Irregulares: gå → gått, se → sett, dricka → druckit, vara → varit.", "Con un momento concreto se usa el pretérito: Igår åt jag (no «har ätit»)."],
    commonMistakes: [
      { wrong: "Jag har varit i Stockholm igår.", right: "Jag var i Stockholm igår.", why: "Con momento concreto → pretérito." },
      { wrong: "Jag har köpat en bil.", right: "Jag har köpt en bil.", why: "Supino de köpa: köpt." },
    ],
    examples: [
      { text: "Har du någonsin ätit surströmming?", translation: es("¿Alguna vez has comido surströmming?") },
      { text: "Vi har bott här i fem år.", translation: es("Llevamos cinco años viviendo aquí.") },
    ],
    contrasts: [{ a: "Jag har sett filmen. (experiencia)", b: "Jag såg filmen igår. (momento concreto)", explanation: "Como el pretérito perfecto frente al indefinido en muchas zonas hispanohablantes." }],
    exercises: [
      { type: "mc", prompt: "Har du ___ i Norge? (vara)", options: ["varit", "var", "varat", "vart"], answers: ["varit"], explanation: "Supino de vara: varit." },
      { type: "mc", prompt: "Jag har ___ nyckeln. (tappa — perder)", options: ["tappat", "tappade", "tappt", "tappar"], answers: ["tappat"], explanation: "Grupo 1 → -at." },
      { type: "mc", prompt: "Igår ___ vi en film. (se)", options: ["såg", "har sett", "sett", "ser"], answers: ["såg"], explanation: "Momento concreto → pretérito." },
      { type: "mc", prompt: "Hon har ___ kaffe hela dagen. (dricka)", options: ["druckit", "drack", "drickat", "druckat"], answers: ["druckit"], explanation: "Supino irregular." },
    ],
  },
  {
    id: "sv:g:passive",
    language: "sv",
    title: "Pasiva con -s",
    cefr: "B2",
    errorCategory: "sv:passive",
    summary: "La forma más común de pasiva es añadir -s al verbo: Huset byggs (la casa se construye). También existe bli + participio para cambios o hechos puntuales.",
    whenToUse: ["Textos informativos, instrucciones y noticias: Butiken öppnas klockan nio."],
    formation: ["Presente: -r → -s: bygger → byggs, öppnar → öppnas.", "Pasado: byggdes, öppnades.", "Supino: har byggts.", "Alternativa: bli + participio: Han blev vald."],
    commonMistakes: [
      { wrong: "Huset bygger av ett företag.", right: "Huset byggs av ett företag.", why: "Pasiva → -s." },
      { wrong: "Butiken öppnar kl. 9. (el sentido es pasivo)", right: "Butiken öppnas kl. 9.", why: "En registro formal se prefiere la pasiva con -s." },
    ],
    examples: [
      { text: "Här talas svenska och engelska.", translation: es("Aquí se habla sueco e inglés.") },
      { text: "Bron byggdes på 1800-talet.", translation: es("El puente se construyó en el siglo XIX.") },
    ],
    contrasts: [{ a: "Man säljer huset.", b: "Huset säljs.", explanation: "Impersonal con man frente a pasiva con -s." }],
    exercises: [
      { type: "mc", prompt: "Butiken ___ klockan nio. (öppna, pasiva)", options: ["öppnas", "öppnar", "öppnades av", "öppnat"], answers: ["öppnas"], explanation: "Presente pasivo: -s." },
      { type: "mc", prompt: "Kyrkan ___ år 1650. (bygga, pasado pasivo)", options: ["byggdes", "byggs", "byggde", "har byggt"], answers: ["byggdes"], explanation: "Pasado pasivo: -des." },
      { type: "mc", prompt: "Boken är skriven ___ en känd författare.", options: ["av", "från", "med", "genom av"], answers: ["av"], explanation: "Agente → av." },
      { type: "mc", prompt: "Här ___ inte rökas. (får)", options: ["får", "fås", "fick", "fått"], answers: ["får"], explanation: "Modal + infinitivo pasivo: får inte rökas." },
    ],
  },
  {
    id: "sv:g:conditional",
    language: "sv",
    title: "Condicional e irrealidad: skulle + infinitivo",
    cefr: "C1",
    errorCategory: "sv:conditional",
    summary: "skulle + infinitivo expresa hipótesis y cortesía; en el irreal pasado se usa hade + supino (a menudo en ambas partes).",
    whenToUse: ["Cortesía: Skulle du kunna hjälpa mig?", "Irreal: Om jag var rik skulle jag resa.", "Irreal pasado: Om jag hade vetat det hade jag kommit."],
    formation: ["Om + pretérito → skulle + infinitivo.", "Om + hade + supino → hade + supino (o skulle ha + supino).", "Tras la subordinada, inversión: Om jag kunde, skulle jag…"],
    commonMistakes: [
      { wrong: "Om jag skulle ha tid, jag skulle komma.", right: "Om jag hade tid skulle jag komma.", why: "En la subordinada se usa el pretérito y en la principal hay inversión." },
      { wrong: "Om jag visste det hade jag kommit. (pasado)", right: "Om jag hade vetat det hade jag kommit.", why: "Irreal pasado: hade + supino en ambas partes." },
    ],
    examples: [
      { text: "Skulle ni kunna tala lite långsammare?", translation: es("¿Podrían hablar un poco más despacio?") },
      { text: "Om jag var du skulle jag ta jobbet.", translation: es("Yo que tú, aceptaría el trabajo.") },
    ],
    contrasts: [{ a: "Om det regnar stannar jag hemma. (real)", b: "Om det regnade skulle jag stanna hemma. (hipotético)", explanation: "Pretérito + skulle marcan la hipótesis." }],
    exercises: [
      { type: "mc", prompt: "Om jag hade mer tid ___ jag lära mig spanska.", options: ["skulle", "ska", "hade", "vill"], answers: ["skulle"], explanation: "Irreal presente → skulle + infinitivo." },
      { type: "mc", prompt: "___ du kunna öppna fönstret?", options: ["Skulle", "Ska", "Hade", "Blir"], answers: ["Skulle"], explanation: "Cortesía → skulle." },
      { type: "mc", prompt: "Om jag hade ___ det hade jag ringt.", options: ["vetat", "visste", "veta", "vet"], answers: ["vetat"], explanation: "Irreal pasado: hade + supino." },
      { type: "mc", prompt: "Om jag var du ___ jag vänta.", options: ["skulle", "ska", "hade", "var"], answers: ["skulle"], explanation: "Consejo hipotético → skulle." },
    ],
  },
];
